package com.pokemon.android.version.model.item

enum class HoldItem(consumable: Boolean) {
    AIR_BALLOON(true),
    ASSAULT_VEST(false),
    BIG_ROOT(false),
    BLACK_BELT(false),
    BLACK_GLASSES(false),
    BLACK_SLUDGE(false),
    CHARCOAL(false),
    DRAGON_FANG(false),
    EXPERT_BELT(false),
    EVIOLITE(false),
    FOCUS_SASH(true),
    HARD_STONE(false),
    LEFTOVERS(false),
    LIFE_ORB(false),
    LUM_BERRY(true),
    MAGNET(false),
    MIRACLE_SEED(false),
    MYSTIC_WATER(false),
    NEVER_MELT_ICE(false),
    POISON_BARB(false),
    ROCKY_HELMET(false),
    SILK_SCARF(false),
    SHARP_BEAK(false),
    SILVER_POWDER(false),
    SOFT_SAND(false),
    SPELL_TAG(false),
    TOXIC_ORB(false),
    TWISTED_SPOON(false),
}