package com.pokemon.android.version.model

enum class Ability(var description : String) {
    ADAPTABILITY("Powers up moves of the same type as the Pokémon."),
    BATTLE_ARMOR("Hard armor protects the Pokémon from critical hits."),
    BLAZE("Powers up Fire-type moves when the Pokémon's HP is low."),
    CLEAR_BODY("Prevents other Pokémon's moves or Abilities from lowering the Pokémon's stats."),
    GUTS("It's so gutsy that having a status condition boosts the Pokémon's Attack stat."),
    IMMUNITY("The immune system of the Pokémon prevents it from getting poisoned."),
    INNER_FOCUS("The Pokémon's intensely focused, and that protects the Pokémon from flinching."),
    INSOMNIA("The Pokémon is suffering from insomnia and cannot fall asleep."),
    INTIMIDATE("The Pokémon intimidates opposing Pokémon upon entering battle, lowering their Attack stat."),
    KEEN_EYE("Keen eyes prevent other Pokémon from lowering this Pokémon's accuracy."),
    LEVITATE("By floating in the air, the Pokémon receives full immunity to all Ground-type moves."),
    LIGHTNING_ROD("The Pokémon draws in all Electric-type moves. Instead of being hit by Electric-type moves, it boosts its Sp. Atk."),
    LIMBER("Its limber body protects the Pokémon from paralysis."),
    LIQUID_OOZE("Oozed liquid has strong stench, which damages attackers using any draining move."),
    MAGMA_ARMOR("The Pokémon is covered with hot magma, which prevents the Pokémon from becoming frozen."),
    MOXIE("The Pokémon shows moxie, and that boosts the Attack stat after knocking out any Pokémon."),
    NATURAL_CURE("All status conditions heal when the Pokémon switches out."),
    NO_GUARD("The Pokémon employs no-guard tactics to ensure incoming and outgoing attacks always land."),
    OVERGROW("Powers up Grass-type moves when the Pokémon's HP is low."),
    OWN_TEMPO("This Pokémon has its own tempo, and that prevents it from becoming confused."),
    RECKLESS("Powers up moves that have recoil damage."),
    ROCK_HEAD("Protects the Pokémon from recoil damage."),
    SHEER_FORCE("Removes additional effects to increase the power of moves when attacking."),
    SHELL_ARMOR("A hard shell protects the Pokémon from critical hits."),
    SPEED_BOOST("Its Speed stat is boosted every turn."),
    STURDY("It cannot be knocked out with one hit. One-hit KO moves cannot knock it out, either."),
    SUPER_LUCK("The Pokémon is so lucky that the critical-hit ratios of its moves are boosted."),
    SWARM("Powers up Bug-type moves when the Pokémon's HP is low."),
    SYNCHRONIZE("The attacker will receive the same status condition if it inflicts a burn, poison, or paralysis to the Pokémon."),
    TECHNICIAN("Powers up the Pokémon's weaker moves."),
    THICK_FAT("The Pokémon is protected by a layer of thick fat, which halves the damage taken from Fire- and Ice-type moves."),
    TORRENT("Powers up Water-type moves when the Pokémon's HP is low."),
    VITAL_SPIRIT("The Pokémon is full of vitality, and that prevents it from falling asleep."),
    VOLT_ABSORB("Restores HP if hit by an Electric-type move instead of taking damage."),
    WATER_ABSORB("Restores HP if hit by a Water-type move instead of taking damage."),
    WATER_VEIL("The Pokémon is covered with a water veil, which prevents the Pokémon from getting a burn.")
}