package com.pokemon.android.version.model

enum class Ability(var description : String) {
    ADAPTABILITY("Powers up moves of the same type as the Pokémon."),
    AFTERMATH("Damages the attacker if it contacts the Pokémon with a finishing hit."),
    ARENA_TRAP("Prevents opposing Pokémon from fleeing."),
    BATTLE_ARMOR("Hard armor protects the Pokémon from critical hits."),
    BLAZE("Powers up Fire-type moves when the Pokémon's HP is low."),
    FLASH_FIRE("Powers up the Pokémon's Fire-type moves if it's hit by one."),
    CLEAR_BODY("Prevents other Pokémon's moves or Abilities\n from lowering the Pokémon's stats."),
    COMPETITIVE("Boosts the Sp. Atk stat sharply when a stat is lowered."),
    DRY_SKIN("Restores HP when hit by Water-type moves\n and increases the damage received from Fire-type moves."),
    EFFECT_SPORE("Contact with the Pokémon may inflict poison, sleep, or paralysis on its attacker."),
    FILTER("Reduces the power of supereffective attacks taken."),
    FLAME_BODY("Contact with the Pokémon may burn the attacker."),
    GUTS("It's so gutsy that having a status condition boosts the Pokémon's Attack stat."),
    HYPER_CUTTER("The Pokémon's proud of its powerful pincers.\n They prevent other Pokémon from lowering its Attack stat."),
    IMMUNITY("The immune system of the Pokémon prevents it from getting poisoned."),
    INNER_FOCUS("The Pokémon's intensely focused,\n and that protects the Pokémon from flinching."),
    INSOMNIA("The Pokémon is suffering from insomnia and cannot fall asleep."),
    INTIMIDATE("The Pokémon intimidates opposing Pokémon upon entering battle,\n lowering their Attack stat."),
    KEEN_EYE("Keen eyes prevent other Pokémon from\n lowering this Pokémon's accuracy."),
    LEVITATE("By floating in the air, the Pokémon receives full immunity to all Ground-type moves."),
    LIGHTNING_ROD("The Pokémon draws in all Electric-type moves.\n Instead of being hit by Electric-type moves, it boosts its Sp. Atk."),
    LIMBER("Its limber body protects the Pokémon from paralysis."),
    LIQUID_OOZE("Oozed liquid has strong stench,\n which damages attackers using any draining move."),
    MAGIC_GUARD("The Pokémon only takes damage from attacks."),
    MAGMA_ARMOR("The Pokémon is covered with hot magma,\n which prevents the Pokémon from becoming frozen."),
    MARVEL_SCALE("The Pokémon's marvelous scales boost the Defense stat\n if it has a status condition."),
    MOXIE("The Pokémon shows moxie, and that boosts the Attack stat\n after knocking out any Pokémon."),
    NATURAL_CURE("All status conditions heal when the Pokémon switches out."),
    NO_GUARD("The Pokémon employs no-guard tactics to ensure\n incoming and outgoing attacks always land."),
    OVERGROW("Powers up Grass-type moves when the Pokémon's HP is low."),
    OWN_TEMPO("This Pokémon has its own tempo,\n and that prevents it from becoming confused."),
    POISON_POINT("Contact with the Pokémon may poison the attacker."),
    POISON_TOUCH("May poison a target when the Pokémon makes contact."),
    PRESSURE("By putting pressure on the opposing Pokémon,\n it raises their PP usage."),
    QUICK_FEET("Boosts the Speed stat if the Pokémon has a status condition."),
    RECKLESS("Powers up moves that have recoil damage."),
    REGENERATOR("Restores a little HP when withdrawn from battle."),
    ROCK_HEAD("Protects the Pokémon from recoil damage."),
    ROUGH_SKIN("This Pokémon inflicts damage with its rough skin to the attacker on contact."),
    SERENE_GRACE("Boosts the likelihood of additional effects occurring when attacking."),
    SHEER_FORCE("Removes additional effects to increase the power of moves when attacking."),
    SHELL_ARMOR("A hard shell protects the Pokémon from critical hits."),
    SPEED_BOOST("Its Speed stat is boosted every turn."),
    SOUNDPROOF("Soundproofing of the Pokémon itself gives full immunity to all sound-based moves."),
    SOLID_ROCK("Reduces the power of supereffective attacks taken."),
    STATIC("The Pokémon is charged with static electricity,\n so contact with it may cause paralysis."),
    STEADFAST("The Pokémon's determination boosts the Speed stat\n each time the Pokémon flinches."),
    STURDY("It cannot be knocked out with one hit.\n One-hit KO moves cannot knock it out, either."),
    SUPER_LUCK("The Pokémon is so lucky that the critical-hit ratios of its moves are boosted."),
    SWARM("Powers up Bug-type moves when the Pokémon's HP is low."),
    SYNCHRONIZE("The attacker will receive the same status condition\n if it inflicts a burn, poison, or paralysis to the Pokémon."),
    TECHNICIAN("Powers up the Pokémon's weaker moves."),
    THICK_FAT("The Pokémon is protected by a layer of thick fat,\n which halves the damage taken from Fire- and Ice-type moves."),
    TINTED_LENS("The Pokémon can use “not very effective” moves to deal regular damage."),
    TORRENT("Powers up Water-type moves when the Pokémon's HP is low."),
    UNAWARE("When attacking, the Pokémon ignores the target Pokémon's stat changes."),
    VITAL_SPIRIT("The Pokémon is full of vitality,\n and that prevents it from falling asleep."),
    VOLT_ABSORB("Restores HP if hit by an Electric-type move instead of taking damage."),
    WATER_ABSORB("Restores HP if hit by a Water-type move instead of taking damage."),
    WATER_VEIL("The Pokémon is covered with a water veil,\n which prevents the Pokémon from getting a burn.")
}